import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.collections': 'Collections',
    'nav.vto': 'Essayage Virtuel',
    'nav.appointment': 'Rendez-vous',
    'nav.location': 'Nos Officines',
    'nav.contact': 'Contact',
    'footer.brand_desc': "L'excellence visuelle en République du Congo (Brazzaville & Pointe-Noire). Fusionnant tradition artisanale et innovation numérique pour redéfinir votre regard.",
    'footer.collections': 'Collections',
    'footer.men': 'Homme',
    'footer.women': 'Femme',
    'footer.sunglasses': 'Solaires',
    'footer.medical': 'Médicales',
    'footer.services': 'Services',
    'footer.vto': 'Essayage Virtuel',
    'footer.appointment': 'Prendre Rendez-vous',
    'footer.promotions': 'Offres Spéciales',
    'footer.contact': 'Contact',
    'footer.location': 'Nos Officines',
    'footer.rights': 'Tous droits réservés.',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions générales',
    'vto.title': 'Essayage Virtuel',
    'vto.subtitle': 'Découvrez comment nos montures s\'adaptent à votre visage grâce à notre technologie de réalité augmentée.',
    'vto.step1': 'Étape 1 : Choisissez votre modèle',
    'vto.step1_desc': 'Sélectionnez une monture pour l\'essayer virtuellement. Vous pouvez en changer à tout moment !',
    'vto.step2': 'Étape 2 : Votre visage',
    'vto.step2_desc': 'Utilisez votre caméra ou une photo pour voir le résultat instantanément.',
    'vto.change_anytime': 'Changez de modèle autant que vous le souhaitez !',
    'vto.allow_camera': 'Autoriser l\'accès à la caméra',
    'vto.camera_desc': 'Pour une expérience optimale, nous avons besoin d\'accéder à votre caméra. Vos données ne sont pas enregistrées.',
    'vto.activate_camera': 'Activer la caméra',
    'vto.init_ar': 'Initialisation AR...',
    'vto.detect_zone': 'Zone de détection faciale',
    'vto.available_models': 'Modèles disponibles',
    'vto.need_help': 'Besoin d\'aide ?',
    'vto.help_desc': 'Prenez rendez-vous dans Nos Officines pour un essayage personnalisé avec nos opticiens.',
    'vto.book_appointment': 'Prendre rendez-vous',
    'vto.upload_title': 'Téléchargez votre photo',
    'vto.processing_photo_title': 'Analyse en cours...',
    'vto.processing_photo_desc': 'Veuillez patienter quelques secondes pour que les lunettes s\'adaptent à votre visage.',
    'vto.select_image': 'Sélectionner une image',
    'vto.take_photo': 'Prendre une photo',
    'vto.take_photo_live': 'Se prendre en photo',
    'vto.upload_from_gallery': 'Télécharger depuis la galerie',
    'vto.mode_selection_title': 'Comment souhaitez-vous ajouter votre photo ?',
    'home.hero_title': 'Le plaisir de voir.',
    'home.hero_subtitle': 'L\'excellence optique rencontre le design intemporel. Découvrez notre collection exclusive en République du Congo, à Brazzaville et Pointe-Noire.',
    'home.hero_btn_catalog': 'Voir les lunettes',
    'home.hero_btn_appointment': 'Prendre rendez-vous',
    'home.partner_title': 'Partenaire Officiel',
    'home.partner_desc': 'Pour vous garantir la meilleure qualité de vision, Bel\'Optique s\'associe à Art Lens, notre partenaire privilégié pour tous vos verres correcteurs de haute précision.',
    'home.feat_1_title': 'Expertise Visuelle',
    'home.feat_1_desc': 'Des examens de la vue précis réalisés par nos optométristes qualifiés avec des équipements de pointe.',
    'home.feat_2_title': 'Design Exclusif',
    'home.feat_2_desc': 'Une sélection rigoureuse des meilleures marques mondiales (Ray Ban, Boss, Fred, Versace...) et des créateurs indépendants.',
    'home.feat_3_title': 'Qualité Garantie',
    'home.feat_3_desc': 'Des verres de haute technologie Art Lens et des montures durables, accompagnés de notre garantie satisfaction.',
    'home.coll_new': 'Nouveautés',
    'home.coll_title': 'Collection Signature',
    'home.coll_view_all': 'Voir tout',
    'home.vto_title': 'L\'expérience d\'essayage virtuel',
    'home.vto_subtitle': 'Essayez nos montures depuis chez vous grâce à notre technologie de réalité augmentée.',
    'home.vto_btn': 'Essayer maintenant',
    'home.catchphrase_title': 'Expertise & Passion',
    'home.catchphrase_text': 'Chez Bel\'Optique, nous prenons soin de votre regard depuis 5 ans. Derrière chaque paire de lunettes, des opticiens passionnés forts de plus de 25 ans d\'expérience, à votre service.',
    'home.brands_title': 'Nos marques prestigieuses',
    'home.testimonials_title': 'Ce que disent nos clients',
    'home.news_title': 'Actualités & Médias',
    'home.news_view_all': 'Découvrir nos actus',
    'news.title': 'Espace Actualité',
    'news.posters': 'Nos Affiches',
    'news.videos': 'Spots Publicitaires',
    'vto.measure_pd': 'Mesurer mon Écart Pupillaire',
    'vto.measure_info': 'L\'écart pupillaire est indispensable pour centrer vos verres. Notre IA le calcule en temps réel en analysant la distance entre vos yeux.',
    'vto.measure_instruction': 'Activez la caméra et regardez droit devant vous.',
    'vto.measure_btn': 'Détecter maintenant',
    'vto.measuring': 'Analyse en cours...',
    'vto.redo': 'Recommencer',
    'vto.ep': 'Écart Pupillaire (EP)',
    'vto.calib_instruction': 'Alignez une carte au format standard (carte vitale, bancaire) dans le rectangle pour calibrer la mesure.',
    'vto.calib_confirm': 'Valider l\'échelle',
    'vto.capture_btn': 'Prendre une photo',
    'vto.download': 'Télécharger',
    'vto.performance': 'Performance',
    'vto.high_fidelity': 'Haute Fidélité',
    'vto.battery_saver': 'Économie d\'Énergie',
    'vto.sharing': 'Génération du message...',
    'vto.capture_success': 'Photo prête !',
    'vto.mobile_optimize': 'Optimisation mobile active',
    'app.step1': 'Service & Date',
    'app.step2': 'Vos Coordonnées',
    'app.step3': 'Confirmation',
    'app.desc': 'Réservez votre moment privilégié avec nos experts opticiens.',
    'app.choose_service': 'Choisissez votre service',
    'app.desired_date': 'Date souhaitée',
    'app.time': 'Heure',
    'app.select': 'Sélectionner',
    'app.continue': 'Continuer',
    'app.your_info': 'Vos informations',
    'app.full_name': 'Nom complet',
    'app.phone': 'Téléphone',
    'app.email': 'Email',
    'app.country': 'Pays',
    'app.city': 'Ville',
    'app.select_city': 'Sélectionner une ville',
    'app.notes': 'Notes supplémentaires (optionnel)',
    'app.notes_placeholder': 'Précisez si vous avez une ordonnance récente...',
    'app.back': 'Retour',
    'app.confirm': 'Confirmer le rendez-vous',
    'app.success_title': 'Rendez-vous Confirmé !',
    'app.success_desc': 'Merci {name}. Votre rendez-vous pour {service} le {date} à {time} a bien été enregistré.',
    'app.email_info': 'Un email de confirmation vous a été envoyé à {email}.',
    'app.back_home': 'Retour à l\'accueil',
    'svc.style': 'Consultation stylistique (Montures)',
    'svc.repair': 'Ajustement et réparation',
    'svc.lens': 'Renouvellement des lunettes',
    'vto.share_whatsapp': 'Partager sur WhatsApp',
    'cat.title': 'Notre Collection',
    'cat.desc': 'Découvrez notre sélection de montures alliant design contemporain et savoir-faire artisanal. Équipées de verres correcteurs Art Lens.',
    'cat.results': 'résultats',
    'cat.sort': 'Trier par',
    'cat.sort_new': 'Nouveautés',
    'cat.sort_brand': 'Marques',
    'cat.load_more': 'Charger plus',
    'cat.new': 'Nouveau',
    'filter.genre': 'Genre',
    'filter.marques': 'Marques',
    'filter.type': 'Type',
    'filter.homme': 'Homme',
    'filter.femme': 'Femme',
    'filter.enfants': 'Enfants',
    'filter.medical': 'Médicales',
    'filter.solaires': 'Solaires',
    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Une question sur nos collections ou besoin d\'un conseil ? Notre équipe est à votre écoute.',
    'contact.info': 'Informations',
    'contact.whatsapp_desc': 'Pour une réponse rapide et personnalisée, contactez-nous directement sur WhatsApp.',
    'contact.email_desc': 'Pour toute demande commerciale ou partenariat.',
    'contact.store_desc': 'Retrouvez-nous dans Nos Officines de Brazzaville et Pointe-Noire.',
    'contact.view_map': 'Voir la carte',
    'contact.send_message': 'Envoyez-nous un message',
    'contact.subject': 'Sujet',
    'contact.message': 'Message',
    'contact.send_btn': 'Envoyer le message',
    'contact.success_alert': 'Message envoyé ! Nous vous répondrons dans les plus brefs délais.',
    'loc.title': 'Nos Officines',
    'loc.subtitle': 'Retrouvez l\'excellence Bel\'Optique dans Nos Officines de Brazzaville et Pointe-Noire.',
    'loc.brazza_title': 'Brazzaville - Hôtel Saphir',
    'loc.brazza_address': 'Boulevard Denis Sassou Nguesso, Brazzaville',
    'loc.pn_title': 'Pointe-Noire - Plateau',
    'loc.pn_address': 'Marché Plateau, en face de ARC Assurance, Pointe-Noire',
    'loc.hours': 'Horaires d\'ouverture',
    'loc.mon_sat': 'Lundi - Samedi',
    'loc.sun': 'Dimanche',
    'loc.closed': 'Fermé',
    'loc.get_directions': 'Calculer l\'itinéraire',
    'vto.estimate': 'Estimation',
    'vto.stable': 'Stable',
    'vto.stabilizing': 'Stabilisation...',
    'vto.try_on': 'Essayer',
    'wa.interest': 'Bonjour, je souhaite avoir plus d\'informations sur le modèle {name}',
    'app.page_title': 'Votre Consultation',
    'app.page_desc': 'Un moment dédié à votre santé visuelle et à votre style. Nos opticiens experts vous accompagnent.',
    'promo.title': 'Offres Exclusives',
    'promo.desc': 'Découvrez nos sélections spéciales. L\'élégance accessible pour tous.',
    'promo.summer_title': 'Collection Été 2026',
    'promo.summer_desc': 'Profitez d\'offres exceptionnelles sur une sélection de solaires (Ray Ban, Carrera, Polaroid) pour préparer les beaux jours.',
    'promo.view_offers': 'Voir les offres',
    'promo.back_title': 'Pack Rentrée',
    'promo.back_desc': 'Découvrez notre offre exceptionnelle sur une monture optique + verres correcteurs Art Lens.',
    'promo.discover': 'Découvrir',
    'promo.selection_title': 'Sélection en Promotion',
    'contact.reviews_title': 'Votre avis nous intéresse',
    'contact.reviews_subtitle': 'Partagez votre expérience avec Bel\'Optique',
    'contact.review_name': 'Nom complet',
    'contact.review_email': 'Email',
    'contact.review_comment': 'Votre avis',
    'contact.review_rating': 'Note',
    'contact.review_submit': 'Publier mon avis',
    'contact.review_success': 'Merci ! Votre avis a été envoyé pour validation.',
    'cat.search': 'Rechercher...',
    'contact.info_contact': 'Contact',
    'contact.error': 'Erreur lors de l\'envoi du message',
    'filter.title': 'Filtres',
    'app.booking_error': 'Une erreur est survenue lors de la réservation.',
    'app.country_congo': 'République du Congo',
    'app.country_drc': 'RDC',
    'app.country_gabon': 'Gabon',
    'app.country_cameroun': 'Cameroun',
    'app.country_other': 'Autre (Préciser en notes)',
    'app.city_other': 'Autre (Préciser en notes)',
    'testimonial.client': 'Avis Client',
  },
  en: {
    'nav.collections': 'Collections',
    'nav.vto': 'Virtual Try-On',
    'nav.appointment': 'Appointment',
    'nav.location': 'Stores',
    'nav.contact': 'Contact',
    'footer.brand_desc': "Visual excellence in the Republic of Congo (Brazzaville & Pointe-Noire). Fusing artisanal tradition and digital innovation to redefine your look.",
    'footer.collections': 'Collections',
    'footer.men': 'Men',
    'footer.women': 'Women',
    'footer.sunglasses': 'Sunglasses',
    'footer.medical': 'Medical',
    'footer.services': 'Services',
    'footer.vto': 'Virtual Try-On',
    'footer.appointment': 'Book Appointment',
    'footer.promotions': 'Special Offers',
    'footer.contact': 'Contact',
    'footer.location': 'Stores',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms and Conditions',
    'vto.title': 'Virtual Try-On',
    'vto.subtitle': 'Discover how our frames fit your face using our augmented reality technology.',
    'vto.step1': 'Step 1: Choose your model',
    'vto.step1_desc': 'Select a frame to try it on virtually. You can change it at any time!',
    'vto.step2': 'Step 2: Your face',
    'vto.step2_desc': 'Use your camera or a photo to see the result instantly.',
    'vto.change_anytime': 'Change models as much as you like!',
    'vto.allow_camera': 'Allow camera access',
    'vto.camera_desc': 'For an optimal experience, we need access to your camera. Your data is not saved.',
    'vto.activate_camera': 'Activate camera',
    'vto.init_ar': 'Initializing AR...',
    'vto.detect_zone': 'Facial detection zone',
    'vto.available_models': 'Available models',
    'vto.need_help': 'Need help?',
    'vto.help_desc': 'Book an appointment in-store for a personalized fitting with our opticians.',
    'vto.book_appointment': 'Book appointment',
    'vto.upload_title': 'Upload your photo',
    'vto.processing_photo_title': 'Processing...',
    'vto.processing_photo_desc': 'Please wait a few seconds for the glasses to adjust to your face.',
    'vto.select_image': 'Select an image',
    'vto.take_photo': 'Take a photo',
    'vto.take_photo_live': 'Take a live photo',
    'vto.upload_from_gallery': 'Upload from gallery',
    'vto.mode_selection_title': 'How would you like to add your photo?',
    'home.hero_title': 'The pleasure of seeing.',
    'home.hero_subtitle': 'Optical excellence meets timeless design. Discover our exclusive collection in the Republic of Congo, in Brazzaville and Pointe-Noire.',
    'home.hero_btn_catalog': 'View glasses',
    'home.hero_btn_appointment': 'Book appointment',
    'home.partner_title': 'Official Partner',
    'home.partner_desc': 'To guarantee you the best vision quality, Bel\'Optique partners with Art Lens, our preferred partner for all your high-precision corrective lenses.',
    'home.feat_1_title': 'Visual Expertise',
    'home.feat_1_desc': 'Precise eye exams performed by our qualified optometrists with state-of-the-art equipment.',
    'home.feat_2_title': 'Exclusive Design',
    'home.feat_2_desc': 'A rigorous selection of the best global brands (Ray Ban, Boss, Fred, Versace...) and independent creators.',
    'home.feat_3_title': 'Guaranteed Quality',
    'home.feat_3_desc': 'High-tech Art Lens lenses and durable frames, accompanied by our satisfaction guarantee.',
    'home.coll_new': 'New Arrivals',
    'home.coll_title': 'Signature Collection',
    'home.coll_view_all': 'View all',
    'home.vto_title': 'The virtual try-on experience',
    'home.vto_subtitle': 'Try our frames from home using our augmented reality technology.',
    'home.vto_btn': 'Try now',
    'home.catchphrase_title': 'Expertise & Passion',
    'home.catchphrase_text': 'At Bel\'Optique, we have been caring for your vision for 5 years. Behind every pair of glasses are passionate opticians with over 25 years of experience, at your service.',
    'home.brands_title': 'Our Prestigious Brands',
    'home.testimonials_title': 'What Our Clients Say',
    'home.news_title': 'News & Media',
    'home.news_view_all': 'Discover our news',
    'news.title': 'News Space',
    'news.posters': 'Our Posters',
    'news.videos': 'Commercial Spots',
    'cat.title': 'Our Collection',
    'cat.desc': 'Discover our selection of frames combining contemporary design and artisanal craftsmanship. Fitted with Art Lens corrective lenses.',
    'cat.results': 'results',
    'cat.sort': 'Sort by',
    'cat.sort_new': 'New Arrivals',
    'cat.sort_brand': 'Brands',
    'cat.load_more': 'Load more',
    'cat.new': 'New',
    'filter.genre': 'Gender',
    'filter.marques': 'Brands',
    'filter.type': 'Type',
    'filter.homme': 'Men',
    'filter.femme': 'Women',
    'filter.enfants': 'Children',
    'filter.medical': 'Medical',
    'filter.solaires': 'Sunglasses',
    'vto.measure_pd': 'Measure my Pupillary Distance',
    'vto.measure_info': 'Pupillary distance is essential for centering your lenses. Our AI calculates it in real-time by analyzing the distance between your eyes.',
    'vto.measure_instruction': 'Activate the camera and look straight ahead.',
    'vto.measure_btn': 'Detect now',
    'vto.measuring': 'Analysis in progress...',
    'vto.redo': 'Retake',
    'vto.ep': 'Pupillary Distance (PD)',
    'vto.calib_instruction': 'Align a standard sized card (credit card, ID) within the rectangle to calibrate measurement.',
    'vto.calib_confirm': 'Confirm scale',
    'vto.capture_btn': 'Take a photo',
    'vto.download': 'Download',
    'vto.performance': 'Performance',
    'vto.high_fidelity': 'High Fidelity',
    'vto.battery_saver': 'Battery Saver',
    'vto.sharing': 'Generating message...',
    'vto.capture_success': 'Photo ready!',
    'vto.mobile_optimize': 'Mobile optimization active',
    'app.step1': 'Service & Date',
    'app.step2': 'Your Contact Info',
    'app.step3': 'Confirmation',
    'app.desc': 'Book your privileged moment with our expert opticians.',
    'app.choose_service': 'Choose your service',
    'app.desired_date': 'Desired Date',
    'app.time': 'Time',
    'app.select': 'Select',
    'app.continue': 'Continue',
    'app.your_info': 'Your Information',
    'app.full_name': 'Full Name',
    'app.phone': 'Phone Number',
    'app.email': 'Email Address',
    'app.country': 'Country',
    'app.city': 'City',
    'app.select_city': 'Select a city',
    'app.notes': 'Additional Notes (optional)',
    'app.notes_placeholder': 'Mention if you have a recent prescription...',
    'app.back': 'Back',
    'app.confirm': 'Confirm Appointment',
    'app.success_title': 'Appointment Confirmed!',
    'app.success_desc': 'Thank you {name}. Your appointment for {service} on {date} at {time} has been recorded.',
    'app.email_info': 'A confirmation email has been sent to {email}.',
    'app.back_home': 'Back to Home',
    'svc.style': 'Style consultation (Frames)',
    'svc.repair': 'Adjustment and repair',
    'svc.lens': 'Eyewear renewal',
    'vto.estimate': 'Estimated',
    'vto.stable': 'Stable',
    'vto.stabilizing': 'Stabilizing...',
    'vto.try_on': 'Try On',
    'wa.interest': 'Hello, I would like more information about the {name} model',
    'app.page_title': 'Your Consultation',
    'app.page_desc': 'A moment dedicated to your visual health and style. Our expert opticians are here to guide you.',
    'promo.title': 'Exclusive Offers',
    'promo.desc': 'Discover our special selections. Accessible elegance for everyone.',
    'promo.summer_title': 'Summer 2026 Collection',
    'promo.summer_desc': 'Enjoy exceptional offers on a selection of sunglasses (Ray Ban, Carrera, Polaroid) to prepare for the sunny days.',
    'promo.view_offers': 'View Offers',
    'promo.back_title': 'Back to School Pack',
    'promo.back_desc': 'Discover our exceptional offer on an optical frame + Art Lens corrective lenses.',
    'promo.discover': 'Discover',
    'promo.selection_title': 'Promotion Selection',
    'contact.reviews_title': 'Your opinion matters',
    'contact.reviews_subtitle': 'Share your experience with Bel\'Optique',
    'contact.review_name': 'Full name',
    'contact.review_email': 'Email',
    'contact.review_comment': 'Your review',
    'contact.review_rating': 'Rating',
    'contact.review_submit': 'Submit my review',
    'contact.review_success': 'Thank you! Your review has been sent for validation.',
    'cat.search': 'Search...',
    'contact.info_contact': 'Contact',
    'contact.error': 'Error sending the message',
    'filter.title': 'Filters',
    'app.booking_error': 'An error occurred during booking.',
    'app.country_congo': 'Republic of Congo',
    'app.country_drc': 'DRC',
    'app.country_gabon': 'Gabon',
    'app.country_cameroun': 'Cameroon',
    'app.country_other': 'Other (Specify in notes)',
    'app.city_other': 'Other (Specify in notes)',
    'testimonial.client': 'Client Review',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
